version: '2'
services:
    testjhipster-app:
        image: testjhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://testjhipster-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=testJhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=testjhipster-elasticsearch:9300
        ports:
            - 8080:8080
    testjhipster-mongodb:
        extends:
            file: mongodb.yml
            service: testjhipster-mongodb
    testjhipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: testjhipster-elasticsearch
